### ISSUE TITLE
Hovering a button on the meal plans list causes a scrollbar to appear

### ISSUE THREAD

**Issue by raiguard** [wr2-cooking-app/cooking-app#46]
![image](https://user-images.githubusercontent.com/3515394/91366529-3a3cf800-e7c1-11ea-8a2c-e14ca4dff4aa.png)

The buttons grow to be too large for their container so a scrollbar appears. This should be fixed before presentation.

**Comment by azakimi123** [comment]
Amanda adjusted the scale size of the buttons
